# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-dependencies:
    docker:
      - image: circleci/node:14
    working_directory: ~/codesandbox
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/cli/node_modules
            - packages/git-extractor/node_modules
            - packages/import-utils/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn build
      - run: yarn test

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/codesandbox
  create-docker-image:
    machine: true
    working_directory: ~/codesandbox
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Docker Sign In
          command: "if [ -n $DOCKER_USER ]; then echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin; else exit 0; fi"
      - run:
          name: Create Dockerfile
          command: |
            cat > Dockerfile <<EOF
            FROM node:14.13.1
            WORKDIR /app
            COPY . /app

            ENV NODE_ENV=production

            CMD ["node", "./packages/git-extractor/dist/index.js"]
            EOF
      - run:
          name: Create Image
          command: docker build -t codesandbox/importers:${CIRCLE_SHA1:0:7} .
      - deploy:
          name: Push Image
          command: "if [ -n $DOCKER_USER ]; then docker push codesandbox/importers:${CIRCLE_SHA1:0:7}; else exit 0; fi"

  deploy-to-staging:
    requires:
      - deploy-staging-approval
    docker:
      - image: curlimages/curl:7.65.3
    steps:
      - run:
          name: Deploy Image
          command: |
            curl --show-error --fail -X POST \
            https://deploy-api.ops.csb.dev/image \
            -H 'Accept: */*' \
            -H 'Authorization: Bearer '$DEPLOY_TOKEN'' \
            -H 'Content-Type: application/json' \
            -d '{
              "env": "staging",
              "image": "githubImporters",
              "tag": "'${CIRCLE_SHA1:0:7}'",
              "deploy": true
            }'
  deploy-to-production:
    requires:
      - deploy-production-approval
    docker:
      - image: curlimages/curl:7.65.3
    steps:
      - run:
          name: Deploy Image
          command: |
            curl --show-error --fail -X POST \
            https://deploy-api.ops.csb.dev/image \
            -H 'Accept: */*' \
            -H 'Authorization: Bearer '$DEPLOY_TOKEN'' \
            -H 'Content-Type: application/json' \
            -d '{
              "env": "prod",
              "image": "githubImporters",
              "tag": "'${CIRCLE_SHA1:0:7}'",
              "deploy": true
            }'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - create-docker-image:
          requires:
            - build-dependencies
      - deploy-staging-approval:
          type: approval
      - deploy-to-staging:
          requires:
            - deploy-staging-approval
            - create-docker-image
      - deploy-production-approval:
          type: approval
      - deploy-to-production:
          requires:
            - deploy-production-approval
            - build-dependencies
            - create-docker-image
